
# elements from ReactDOM
# https://github.com/facebook/react/blob/master/src/browser/ReactDOM.js

module.exports =
  a: false
  abbr: false
  address: false
  area: true
  article: false
  aside: false
  audio: false
  b: false
  base: true
  bdi: false
  bdo: false
  big: false
  blockquote: false
  body: false
  br: true
  button: false
  canvas: false
  caption: false
  cite: false
  code: false
  col: true
  colgroup: false
  data: false
  datalist: false
  dd: false
  del: false
  details: false
  dfn: false
  div: false
  dl: false
  dt: false
  em: false
  embed: true
  fieldset: false
  figcaption: false
  figure: false
  footer: false
  form: false # NOTE: Injected see `ReactDOMForm`.
  h1: false
  h2: false
  h3: false
  h4: false
  h5: false
  h6: false
  head: false
  header: false
  hr: true
  html: false
  i: false
  iframe: false
  img: true
  input: true
  ins: false
  kbd: false
  keygen: true
  label: false
  legend: false
  li: false
  link: true
  main: false
  map: false
  mark: false
  menu: false
  menuitem: false # NOTE: Close tag should be omitted but causes problems.
  meta: true
  meter: false
  nav: false
  noscript: false
  object: false
  ol: false
  optgroup: false
  option: false
  output: false
  p: false
  param: true
  pre: false
  progress: false
  q: false
  rp: false
  rt: false
  ruby: false
  s: false
  samp: false
  script: false
  section: false
  select: false
  small: false
  source: true
  span: false
  strong: false
  style: false
  sub: false
  summary: false
  sup: false
  table: false
  tbody: false
  td: false
  textarea: false # NOTE: Injected see `ReactDOMTextarea`.
  tfoot: false
  th: false
  thead: false
  time: false
  title: false
  tr: false
  track: true
  u: false
  ul: false
  'var': false
  video: false
  wbr: true

  # SVG
  circle: false
  defs: false
  g: false
  line: false
  linearGradient: false
  mask: false
  path: false
  pattern: false
  polygon: false
  polyline: false
  radialGradient: false
  rect: false
  stop: false
  svg: false
  text: false
  tspan: false